### ISSUE TITLE
Tokenization error.

### ISSUE THREAD

**Issue by emmanuelulloa** [troy351/emmet-monaco-es#111]
I get the following error in the console:
`Uncaught Error: Cannot read properties of undefined (reading '_tokenization')

TypeError: Cannot read properties of undefined (reading '_tokenization')
    at emmet-monaco.min.js:1:89850
    at pr (emmet-monaco.min.js:1:90247)
    at Object.provideCompletionItems (emmet-monaco.min.js:1:91855)
    at e.provideCompletionItems (standaloneLanguages.ts:601:71)
    at Object.provideCompletionItems (standaloneLanguages.ts:341:19)
    at suggest.ts:84:44
    at async.ts:30:14
    at new n.Class.derive._oncancel (winjs.base.raw.js:1641:1)
    at Object.c [as asWinJsPromise] (async.ts:29:9)
    at suggest.ts:84:12
    at errors.ts:33:12`
    
For more info see the following example: https://codepen.io/emmanuelulloa/pen/vYQgoRR?editors=0010

**Comment by emmanuelulloa** [comment]
Monaco editor is being loaded through a Worker URI and Emmet-Monaco-es is being loaded as a regular script, although both are from the same CDN:
https://unpkg.com/monaco-editor@0.39.0/min/vs/loader.js
https://unpkg.com/emmet-monaco-es/dist/emmet-monaco.min.js

**Comment by emmanuelulloa** [comment]
Never mind is working now.  I just change the CDN and it worked out.
